### ISSUE TITLE
Initialize weights

### ISSUE THREAD

**Issue by amlarraz** [tuckerdarby/tf-deeplab-v3#2]
Hey! Nice work @tuckerdarby, thanks! I'm trying to train and I see you haven't Initialize weights, this use a random initialization instead a pretrained weights?

**Comment by tuckerdarby** [comment]
Hello!

I handled the layers a bit differently between standard conv layers and atrous conv layers. The atrous conv layers have their weights initialized using Xavier and biases are constant. The standard conv layers use the layers library in TF. I was under the assumption that the library initializes the weights, but if it doesn't that would be a great point of improvement for the net.

All in all Google recently released their official version of deeplab v3 implemented in Tensorflow, so I won't be doing any more work on this repo.

**Comment by amlarraz** [comment]
Hey, thanks!! No problem, I've seen the notices, thanks a lot for your work and your help!
